### ISSUE TITLE
Party members are not at party leaders location

### ISSUE THREAD

**Issue by kitocole** [IdleLands/IdleLands#145]
![image](https://cloud.githubusercontent.com/assets/14023882/18479386/9bbcf83c-7989-11e6-8c78-5d871bc744b6.png)

My party

http://imgur.com/a/pDVuI

Top left/bottom right are our locations.

Neither have anything but seeker and sharpeye on. I don't see any other party members either

**Comment by Anexes** [comment]
Was going to post about this, but you beta me to it :P

In my experience, players still teleport to the leader, but they don't actually follow each other, so everybody just wanders off.

**Comment by kitocole** [comment]
You are right Anexes. Just got into a party, everyone going their own way.

**Comment by sidawson** [comment]
Hrm. Paranoid my recent changes in this area might have screwed things up. Can't see it (yet) though. The key line of code is here: https://github.com/IdleLands/IdleLands/blob/master/src/plugins/players/player.js#L210

basically, passing in nothing sets overrideFollow to false in pickRandomTile, which runs this code:

https://github.com/IdleLands/IdleLands/blob/master/src/plugins/players/player.movement.js#L190-L195

which should (in theory) just return the last tile of the leader, which will always be valid, thus skipping the core "keep picking random tiles" loop in player.moveAction, here:

https://github.com/IdleLands/IdleLands/blob/master/src/plugins/players/player.js#L215-L222

the only exceptions I can think of would be if the non-leader party members weren't _allowed_ to enter the tile, in which case they'd go elsewhere. The possible conditions are listed here:

https://github.com/IdleLands/IdleLands/blob/master/src/plugins/players/player.movement.js#L38-L57

Although I'd posit that in general they're fairly rare, and unlikely to be the problem here.

[note that if we don't successfully follow the leader on the first attempt, then we will move off, because we'll drop into the loop, where we're passing in overrideFollow=true, here:

https://github.com/IdleLands/IdleLands/blob/master/src/plugins/players/player.js#L220
]

I went back in history in both files to before my "lock bug fix" commits, and, far as I can see, these bits of code haven't changed. I may have missed something.

**Comment by SecondSkinPT** [comment]
I have noticed this error too. Can i posit that the required coding is there...albeit not in the proper format. Thanks for any future updates! The pets are great!
