### ISSUE TITLE
Reduce CPU usage by not calculating stats every time they're needed

### ISSUE THREAD

**Issue by KennethShen** [IdleLands/IdleLands#300]
Currently, [gainXp](https://github.com/IdleLands/IdleLands/blob/25f1332c20e2ded5453ae2f1eb440c12f6c569f9/src/plugins/players/player.js#L152) recalculates the player's xp value every time it's called. Unfortunately, this happens **every** time the **any** player takes a step. 

Possible solution: Cache the xp value and only update it on equipment/personality/achievement changes.

The underlying problem may be the use of `liveStats`. Most of the time, stats won't change and don't need to be recalculated.

**Comment by seiyria** [comment]
It's tough to say that most of the time stats don't change, because generally they're calculated most often when they do. There might be some changes I can make, but the biggest one that comes to mind is possibly the introduction of a dirty flag on stats to see if they need to be recalculated. It will take some time to devise that and if it doesn't pan out, I'll just end up ad-hoc'ing a solution for xp.
