### ISSUE TITLE
Guilds

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#35]
- [x] donate resource [gold, crystals, guild resources] to guild buttons
- [x] if you have a guild, but aren't in the members list, you were kicked (should be checked on player login)
- [x] guild taxes should work
- [x] cannot disband guild. can only leave guild if there are other leaders.
- [x] buildings have toggles on them which make them active. only one of each category can be active (categories: garden, event enhancer, etc). like personalities, toggling one will untoggle the rest.
- [x] ~~badge/sidebar notification if guild mod++ and have member applications~~
- [x] Some guild buildings (stash, guildhall) should start at level 1, the rest need to be bought first
- [x] Make sure guilds are a sufficient infinite gold sink
- [x] Make sure guilds utilize all resources (stone, gold, astralium, wood) fairly equally
- [x] salvage festival
- [x] Salvaging should add resources to the player resources area
- [x] personality to auto-donate salvaged stuff to a guild.
- [x] ~~Action: Cull guild members inactive for X days~~
- [x] Allow for viewing all guilds if you do not have one (new REST API call)
- [x] Allow for multiple guild modes: open recruitment, apply, and closed recruitment
  - [x] Open recruitment is they click, they join (should be able to see a recruit message on the box)
  - [x] Apply would put the person in a queue (should be able to see a recruit message on the box)
  - [x] Closed recruitment would mean the guild is invite-only
- [x] Guild invites and applications need to be stored in a new collection for easy clearing out
- [x] Inventory update: Salvage single item, salvage all items
- [x] inventory update: donate resource to guild
- [x] Allow for buildings, building slots still (via BP)
- [x] A person can have multiple invites sent to them, and they can apply to multiple guilds
- [x] Guilds should continue to have MOTDs
- [x] Guilds should continue to have tax options available for players, as well as self-tax
- [x] 3 ranks: leader, admin, mod. only leader can disband, but leader can promote other leaders.
- [x] 4 tabs: overview, members, buildings, manage
- [x] ~~When sending pets on pet adventures, you should be able to loan pets from other guild members (?) which would earn a guild currency (?) for a guild gacha roll (?)~~
- [x] Re-add treasurehunter and salvager personalities
- [x] Update the event message parser to include new guild related things
- [x] Salvage: Character/Item/Salvage. Pets should still offer salvage boosts. Permanent upgrade to increase salvage results.
- [x] ~~Audit log for guild actions (should last 7days, be a REST API calls)~~
- [x] System message when a guild is founded
- [x] ~~Guild member application push notification~~
- [x] New gacha banner for guild resources (drops astralium, gold, stone, wood)
- [x] Guild names should be parsed with censor-sensor [same with tags]
- [x] Guilds should still have up-to 6 character tags, min of 2.
- [x] Update astral gate with guild resource rewards
- [x] Update pet adventures with guild resource rewards/new mission
- [x] update personal quests with guild resource rewards
- [x] update global quests with guild resource rewards
- [x] update adventure rewards with guild rewards
- [x] update quest statistics with salvaged guild resources
- [x] GM commands to give gold/astralium/wood/stone to guilds
- [x] Guild upgrade: buy a discord channel/role for your guild members
	- [x] requires crier level 1
	- [x] check discord stuff on each guild upgrade and each create
	- [x] disband guild removes discord channel / role
	- [x] discord members should be given a role of Guild: Whatever on login if the role exists
- [x] make guild buildings work
	- [x] gardens should divide their % among all players in the guild (if 10 people are in the guild and the garden buffs by 10%, the total buff for each player is 1%)
	- [x] factories need to generate stuff on a tick
	- [x] ~~crier periodically sends a message to #guild-recruitment in discord every X hours as well as town crier messages and in game chat messages. probably once every X ticks~~
	- [x] academy needs to cap members properly
	- [x] stash needs to work properly / display properly in guild overview
	- [x] enchantress should increase the cap every 50 levels, and have a chance of doing a better event than normal
	- [x] merchant should improve item level by 1 per merchant level for items generated by the players
	- [x] tavern keep needs to buff gambling somehow
	- [x] fortune teller should improve the shift to positive by some logarithmic amount as well as have a chance to generate xp/gold/hp on providence
	- [x] generators need to work on a tick
    - [x] witch doctor should skew negative with higher boosts
	- [x] raid portal allows for farming bosses starting at a certain level (probably 100) + 50 per level in raid portal. every boss should have a variable amount of HP based on how many players attack it. all online players in a guild should fight together on the same team. the popup should list all possible fights, its level, and a randomly generated seeded reward for that level. all players with levels >= the boss level get that item if it succeeds. each attempt should cost gold (scaled with # players & the tier) and injury checks should happen as normal (fail if anyone is too injured).
	- [x] raid bosses should track a new "raid battles" statistic - track # raid battles, # wins, and wins for each tier (Tier1, Tier2, Tier3, etc) - this should include titles
	- [x] raid should request all players on all shards (in iBattlePlayer form), then delay like 1000ms, then start battle
	- [x] raid bosses should scale their stats additionally based on the number of participants (pets do not count) - 10000 hp per player, 100 stat per player
	- [x] raids should offer rewards: lots of gold/xp, an RNG scaled item (possibly including trinkets in the RNG slots), and pet crystals
	- [x] item generator should consume some resources (update desc)
	- [x] scroll generator should consume some crystals (update desc)
- [x] Some buildings get an "active" ability (raid portal, for example) which pops up a menu.

**Comment by sedgwick** [comment]
["End Game"](https://github.com/IdleLands/IdleLands/issues/33)
I feel guilds, from IL3, are where there could be way more room for expansion. As it was before, only mods and guild leaders had any real stuff they could do mechanically, everyone else was just an idle contributor to a guild through resources or gold. So to add on to SirOnion's guild raid bosses idea, just more guild ideas in general. Since it does come down to community options to help longevity of the game, that's the most important area.  

Thoughts for additions:
- More and larger guild bases
- Guild only festivals, significant gold/resource sinks as a large guild can rack up a lot of gold. I know Cartographer's Guild was sitting up in the 70 billion range with 1% tax, so imagine what an active and larger guild could do.
- Pet Adventures for guild resources?
- Thinking of pet adventures made me think of guild adventures. Though instead of selecting characters, everyone online participates, with those who are only on for part of the time receiving a partial bonus on next logon. Needs some more thought on how this would fully work/reward.

**Comment by sedgwick** [comment]
@seiyria  "I think salvaging per player might be feasible and reasonable now that I track materials and resources separately, with a way to auto-donate to a guild I think we'll be good to go in that regard."

Something for players who are not in a guild, and do not wish to join one, to do with salvage resources. Quests https://github.com/IdleLands/IdleLands/issues/59 are one way, maybe they sell for cheap with increasing price depending on rarity of resource?

**Comment by JukeDragh** [comment]
To avoid having everyone conglomerate into one giant Guild you could:
- Give bonuses for Owning the guild to incentivize starting one instead of joining.
- Make the bonuses a pool that is divided among members so that large guilds with large bonuses 
  are about as effective as small guilds with small bonuses
- Have a fee associated with joining a guild that scales with the number of people in it so newer 
  players who don't have as much gold join smaller guilds.
- The guild itself might have operating costs based on the number of player in it to incentive downsizing.

**Comment by Brooke-Renna** [comment]
Possible ideas for stopping all players conglomerating would be to encourage staying with a guild (providing you were already in one) so people don't jump ship into the fastest growing or largest guild, so perhaps:
- Penalties for switching guilds rapidly, or a large cooldown on being able to switch guilds
- Achievements or other bonuses for spending a certain amount of time in one guild, beyond just sunk resources.
- Adding to Juke's joining fee suggestion, as well as the size of the guild in terms of number of members, perhaps the fee could scale with how well the guild is doing (measured through rankings or resources or some suitable measure)

**Comment by seiyria** [comment]
For guild buildings, it might also make sense to have a point buy system (with an upgradeable point system). This would allow guilds to expand to a point, but depending on buildings (which still need TBD) to specialize.

**Comment by seiyria** [comment]
Possible buildings (ported from IL3):

- Academy - previously, controlled roster size. possibly, offer more frequent upgrades / higher base roster size this time. this building should always exist.
- enchantress - previously, buffed enchant values for specific enchantress. this time, could buff all enchant events (sometimes, not always)?
- fortune teller - previously, buffed providences at guild FT. this could slightly buff providence events randomly (not always)?
- large garden - previously, buffed combat stats. it could still do that, but maybe it would boost offense stats and be renamed (offense garden)
- medium garden - previously, buffed rare stats. we don't have those anymore, so we could add a defense stat garden and rename it to defense garden
- small garden	- previously, buffed basic stats. we could do this again and make it very weakly buff xp/gold and strongly buff hp? maybe?
- guild hall - previously, you needed to upgrade your guild hall to upgrade other buildings. was that an ok system? if so, it could work with the point buy system and increase the number of points available (but be very expensive to upgrade)
- guild shop - previously, let you buy items while in guild hall. this time, maybe a "guild proprietor" and have him buff bought items?
- mascot - previously... it existed. it could still exist I guess?
- tavern - previously... it existed. it buffed guild gambling to a point where it was too ludicrous. so maybe it could still buff gambling in different, non-OP ways. it could also do other things.
- teleport - previously, existed. it probably wont be brought back because ATM there is no plan for a formal guild hall.

Some new ideas:

- generators - these buildings could generate resources on an interval (as a form of offline progress). resources generated: astralium, gold, stone, wood. you would upgrade each generator differently
- bank - upgradeable guild bank to increase storage of materials.
- market - upgradeable area that can be used to buy/sell materials based on a market rate

If we're doing guild vs guild raids, the following might make sense:

- stash - hide X materials so they are not plundered when attacked by another guild
- defense units - these units accompany your guild in combat when defending - possibly you could hire X units and choose a class for them and they would defend
- offense units - these units accompany your guild in combat when attacking - similarly, you could hire X units and choose class for them

If we're doing guild v raid boss raids, the following might make sense:

- training ground - uhh... no idea
- raid teleporter - increase the max level of bosses you can fight

Looking for other building ideas. Pretty much anything is on the table.

**Comment by seiyria** [comment]
zig building ideas:

instead of resource generators, item factories:

- generate buff scroll and distribute to all online players
- generate crystal and distribute to all online players
- generate item to distribute to all online players

factories would cost upfront materials, run for a certain amount of time, and when done, distribute.

upgrading the factories would upgrade the raw stats on an item (so, scrolls would not generate with a % of player, but based on the level of the factory. items same. crystals might increase in quantity)

costs would obviously be materials, and vary based on ... ???

**Comment by seiyria** [comment]
boozle barracks ideas:

Guild mods can review players' current loadouts (class, combat stats, subclass skills) and pick up to four of them for the Guild Barracks.  When GvG occurs, this set of 4 players faces off against another guild's Barracks lineup.  Player loadouts can only be active for up to 7 days at a time (can be manually cancelled) to prevent mods from sticking one person who's massively OP in there to mow everyone down forever.

zig suggests that GvG might not work well due to guild stacking

**Comment by seiyria** [comment]
@sedgwick's original idea for global boss quests (thanks to boozle):

What if guild raids worked like global quests did?  Guild raid bosses would be massively OP but however much damage you dealt to them would be added to your guild's score, and at the end, all participating guilds would get bonuses based on how they did.

So there would be a current raid boss that would have a lot of HP (probably in the billions) and get plinked down by every online guild member. The top 3 guilds would get a reward (like global quests) and all runner up guilds would also get something.

You would only be able to attack the boss once every X time (hour?). It would expire in a week, similar to global quests.

**Comment by sedgwick** [comment]
- Mascot - Should exist for everyone instead of taking a slot. Guild leaderboard for tracking. Previously no one used it because slot space was so limited. Very expensive but bragging rights only seems like a good system for that.
- I'm okay with a smaller roster size, say 10, before you need to start upgrading the academy to add more members. Considering our current average player count, starting with a base roster over 10 seems a bit much.
- Enchantress - With the enchantress supporting the guild, base enchant value could go up, I think that's a great idea. To spice it up a bit more, each level could add a very tiny percent chance of being able to double enchant an item, if available, probably to a cap at some level. So double enchant would hit two different stats with one enchant event, and add +2 to the enchant level of the item. If the item only has +1 remaining, then it wouldn't fail on double enchant, just run it as a +1 (and note something like "the enchantress was going to provide a critical upgrade but failed because of enchant cap") When we consider that enchant costs scales per player gold, this will help justify those significant gold cost per enchant when we're rarely seeing anyone capping an item before ascension or item swap.
- Generators - level increases should probably not reduce frequency of resources, just resources provided.
- Love the market idea, and I think there should be markets for non-guild players. We had discussed that non-guilded players could get resources too, still pending, but a non-guild player could have the option to sell at a default low price market while guild members have one they can upgrade and increase the value of.

I've got some other ideas I can post later on.

**Comment by sedgwick** [comment]
- Barracks idea - Anytime you can set select guild members for something would need to done really carefully. As it is written in the comment above there would be an automatic disband of the current line up after 7 days, but nothing to stop you from just putting that group right back in again. It could end up being a bit exploitative with a few key guild members always having the role. I know it's still all undecided but anything from the barracks would hopefully apply across all members of guilds, or cooldown on who can be in the barracks lineup.
- Factories - I like the idea, it gives you something you can manage outside of building levels with something **active** you can use as a guild member. IL3 was very passive (sure there was the guild hall but that was always tricky to get to/expensive).
- guild v. guild section on training grounds - some ideas could be generating guild party vs. guild party battles. Winners get rewards but losers do not lose XP/gold or gain injuries, as it is all in good sport with allies. Players individually go on a cool down so you can run the training grounds multiple times until all online guild members are on training grounds cooldowns. higher levels could reduce cooldown times or increase rewards for winners.
- offense and defense units in guild v guild raids - Selecting classes as an option just means that you'll have people selecting whatever happens to be the most powerful/unbalanced class of the week. I like the idea of hiring mercenary defenders/attackers, but they should be random. Perhaps variable levels, like a level 1-50 group that's X gold, 50-100 that's 3X gold, etc. Would need a cap so you can't just spam 10,000 level 1's as meat shields or 10,000 high levels as attackers. Perhaps the mercenary hiring building level would allow you to hire more mercenaries, and at certain building levels unlock the higher tiers of mercs.
- tavern - if you aren't keen on guild gambling, then the tavern could be a place to help you form guild parties. I know selective parties has been a debated topic, but being able to non-randomly get with a group of people who you are already trying to actively work together with would be nice. So I haven't any ideas on what you could do for building levels, but the building could be something you assign yourself to. I toggle myself to be 'in the tavern' so if enough guildies are in the tavern, and someone gets a party event, you try and form one with those also in the tavern.
- guild shop - generate a Merchant event with a cooldown per player. Higher levels gives a higher merchant bonus.
- Fortune Teller - Could provide a safe way to remove a providence among other options. Pay out some gold to remove your bad fortune without taking the gamble in the pools/lake and getting something even worse.


The gardens - I think there could be a lot of potential in expanding how the gardens worked from IL3. Imagine breaking this down per attribute and then you could have melee focused guilds who like to recruit fighters/rogues because they have a strong STR/AGI gardens, or a mage's guild with a super INT Garden. Separate gardens = more individuality per guild = more options = more gold sinks.

- Garden of Strength
- Garden of Intelligence
- Garden of Dexterity
- Garden of Agility
- Garden of Constitution
- Garden of Luck
- Garden of Experience
- Garden of Gold
- Garden of Health
- Garden of Mana

Let everyone have access to all gardens. General guilds will go for a little of everything, focused guilds can specialize, gold sinks all around, and not having to figure out how to consolidate down to 3 gardens.

**Comment by seiyria** [comment]
Some building costs should scale linearly, others exponentially. For example, it should be exponential cost to add more guild members.

**Comment by seiyria** [comment]
Deferred:

- Market
- audit log
