### ISSUE TITLE
guilds

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#35]
bring back guilds and guild halls

**Comment by Anexes** [comment]
Suggestion:
     Strategist (Raid Planner? Logistics Center? War Room?)

Purpose:
     Help players defeat very difficult (or perhaps impossible,) bosses by creating "Raid Parties."

Possible Abilities:
     Lets you create parties and choose who is in them.
     Increases the max members in a party.

Possible Limitations:
     Players must be in guild hall to be added to Raid Party?
     Benefits only apply to Raid Parties?
     Must be very high/max level or ascended to participate in a Raid Party?

**Comment by seiyria** [comment]
Welp, here's a big one (in addition to the already existing crap that would need to be done):

a whole separate playable game for guilds (where guilds are actually managed and stuff in idlelands, but you can "play" in your guild area).

creating a guild would also create a guild hall (as per usual). you could also go to "guild.idle.land" and the game would log you in (or try to) based on your current player. you'd log in as "avatar of X" where X is your player. anything done would be shared between games (although, this creates some concurrency issues because there is no sync from the db, just pushing to it in both cases).

things you could do:

* create your guild hall
* farm(?)
* craft(?)
* sell(?)
* chat (would be sync'd)

the tricky part here is that you'd have to be logged into both services for this to work, but it really is a separate experience. ideally, this would actually be streamlined into idle.land but given it's not-idle nature, that might not make sense.

**Comment by sedgwick** [comment]
Some other guild ideas I had or we discussed earlier:

* Certain collectibles required (possibly new guild related ones, charters, etc.) to start certain projects.
* Guild achievements, Guild rewards. Beyond traditional achievements, I imagine some achievements where you are required to have a party of of exclusively guild members to earn. Things like killing certain bosses could be one, and I think the guild party achives (or others too) could offer trophies to your guild hall. Something like being able to [display your kill](http://i.imgur.com/TVHs6Bt.jpg). Of course, it would be tricky to set that up, so Guild Halls could have a way to help you form guild only groups?
* Possible gathering for resources to start constructing buildings beyond the first building. I imagine the guild hall itself would just require typical requirements up to this point, a set of collectibles or required level, something presently in game and not a new mechanic to start a guild.
* Gathering, as it relates to farming: The first idea that comes to mind for a farming gather system would be plants related to different stat. So a jester might want the guild to grow "4 leaf clover patch" for luck resources while a fighter would want Y plant for STR, or Z plant for some CON. The resources would be used for the modifiers in crafting in the crafting scenario I wrote below. Just one idea, but it could be reflavored for any other way to gather (mining).
* Crafting: I think it would be cool if you could add specific item modifiers to a crafted item, but probably after you've already equipped an item that has the modifier. For example, once you've already found an item with "googolplex-pronged" you could create a new item (possibly alter old ones?) that had this prefix on it for X resources depending on the score it provides.
* Many of the old buildings would still work, but the enchantress could be a problem since enchant events are presently a bit rare, and the GuildLands version would let it be something you could go to whenever you like.
* The Merchant works differently in this version of IdleLands, and there is a bit of overlap now between the enchantress building and the merchant shop that could result in lots of enchants really quick (if you have the gold, and maybe that's enough to balance it?). A higher level merchant shop would raise the merchantBonus, increasing the chance that it would also generate an enchant instead of an item. But then again, the GuildLands version let's a player walk right up to the shop, so this might have to work differently anyways.

**Comment by AscendedGravity** [comment]
Some of this is probably already implied, but putting it here for record.

1. Gathering
   * Gathering of resources would require the necessary tools, seeds, and maybe some with achievements
   * Chance a harvest or material get can fail or provide low yield
   * Fishing(?) Because fishing is awesome!
   * Resources have re-spawn times
2. Selling
   * 100% player driven economy or "Global Shop" like involvement that would buy things at low prices(?)
   * Guild to Guild trading (that can be initiated by only Guild leader or players the GL assigns)
   * Trading posts need to be constructed in another guild to be able to trade with said guild (?)
3. Other Thoughts
   * Guild Leader can set taxes on members the could be collected on a set basis. 
   * Guild name of player listed in IL Play chat ( [Name], the [Title] [of Guild] ) (?)

**Comment by seiyria** [comment]
possibly some compromise here where guilds generate resources and can upgrade resource generators. resources are used to construct new buildings, etc and can be traded on a global market.

**Comment by seiyria** [comment]
Lets do something with the best of both worlds. The introduction of guilds will allow for item salvaging, that is, taking an item and breaking it down into its components. Guild buildings will require resources and gold for upgrading or constructing (or re-constructing, but tear-down will only cost gold).

Pets will be able to gnash and tear and rip and ultimately salvage items. Different pets will have different salvage rates. Some pets will not be able to salvage. There will be 4 component resources: 

* Wood (this is gotten at a rate of 1 per (DEX+STR)/10)
* Clay (this is gotten at a rate of 1 per (AGI+CON)/10)
* Stone (this is gotten at a rate of 1 per (INT)/20)
* Astralium (this is gotten at a rate of 1 per LUK/100 + variable amounts for special stats (hpregen, silver, etc)

**Comment by seiyria** [comment]
@sedgwick also suggests to have an auto-salvage personality instead of autosell
