### ISSUE TITLE
Providence nerf makes xp providence too powerful when lowering xp

### ISSUE THREAD

**Issue by KennethShen** [IdleLands/IdleLands#431]
Ever since providence had been nerfed to actually lower your level when you reach 0 xp, there have been reports of players losing levels at a severe rate.

This is due to the xp providence removing a level when your xp goes to 0 (which is fine) but **also** [setting your xp to 0](https://github.com/IdleLands/IdleLands/blob/fe59a3947df6ee45515e5583d32961592426203f/src/plugins/events/events/Providence.js#L81) (which is definitely not fine).

In addition to that, any extra xp over the max xp when gaining xp (from any source, not just providence) is lost and does not carry over to the next level.

Ideally, any extra xp gained/lost should carry over into the next/previous level.

The xp providence should also be lowered in effectiveness. Possibly make the range from -0.5 * maxXP to 0.5 * maxXP instead.

The probability of xp/level events should also be lowered. Providence is too easy to get now and severe changes in xp/level are not fun.

Additionally, it may also be too easy to accidentally wander into the fate lakes from Dark Tower -3. There is no real opt-out option like with the fate pools or the Minotaur Maze or Water Plane -1 (scared of the dark on the rope descent).

**Comment by TheParanoidBaboon** [comment]
With one event every 5 seconds, I went from lvl 23 to lvl 1 in a few minutes - and I'm not alone in that situation. Is it really the intended purpose of the lake ? Sacrificing all your levels and gold for the +5% item score of the achievement ? (and watever else was on the map I didn't get). It's harsh, and might need some very big warning signs. It's not cool right now.
Oh, and I would have appreviated to keep my personalities. I have to grind back from 1 to 18 to be drunk again. Losing "Drunk" is annoying, especially for so long, Can't it be permanently unlocked via an achievement after reaching lvl 18 ?

**Comment by seiyria** [comment]
@KennethShen I've already lowered the probabilities of both, fundamentally. The only change I'd be willing to make here is to carry over lost XP and not entirely remove xp on downlevel. I don't see the -100%:+100% change as explicitly terrible, because it's a fair chance to go either direction.

We're removing the DT-3 entrance, and that will be the end of it.

@TheParanoidBaboon Achievements are 100%, entirely optional. If you want it, you're welcome to go for it. The intended purpose of the lake was somewhere to gain Providence faster. The achievement came far after. It doesn't matter if it's "not cool" it was part of the game that I wanted to add.

Some achievements are permanent. The one that grants Drunk is not, nor will it be.
