### ISSUE TITLE
death messages

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#482]
- unlocked via achievements
- a few defaults ("has died", "has vanished into thin air") maybe more
- needs a dropdown on Play

**Comment by JoeSyr** [comment]
<<Player>>'s not pining for the fjords! <<Player>> has passed on! <<Player>> has ceased to be! <<Player>> has gone to meet their maker! <<Player>>'s a stiff! Bereft of life, <<Player>> rests in peace! <<Player>>'s metabolic processes are now history! <<Player>>'s off the twig!<<Player>>'s kicked the bucket, 'e's shuffled off 'is mortal coil, run down the curtain and joined the bleedin' choir invisible!! THIS IS AN EX-<<Player>>!

Source and for further riffing: http://montypython.50webs.com/scripts/Series_1/53.htm

Also for consideration: Just make this lot an easter-eggy specific to pet parrots dying.

**Comment by AscendedGravity** [comment]
- %player watched their innards become outards
- %player has a critical failure and pays the price (via Critical achievement)
- %player tested their fate but was nerfed (via Fateful achievement, too meta???)
- %player soaked up too much damage (via Sponge achievement)
- %player was slayed (via Slayer achievement)
- %player collected their things and went to a happier place (via Collector achievement)

**Comment by sedgwick** [comment]
@seiyria maybe a random option as well?

**Comment by Anexes** [comment]
@seiyria Maybe the death message is decided by your title? Then you don't need another dropdown.
@sedgwick Not sure how random would be a thing. No title?

I don't necessarily love the idea of death message being tied to title, because you might like one achievement's death message but not its title (or vice versa,) but it seems like a good way to work it into the existing setup and it makes a lot of sense to me that they'd be tied to each other.

**Comment by seiyria** [comment]
I think that's reasonable. No title would be a generic message. In this
case, there would be no shuffling.
