### ISSUE TITLE
A short log

### ISSUE THREAD

**Issue by TheParanoidBaboon** [IdleLands/IdleLands#488]
When I come back from idling hours, I see the last events in the log. That fine. But that would be nice if there was some kind of "short log", that would keep only "important stuff" for a longer time. I would be so happy to see I got 2 achievements, fought 1 boss and got 1 collectible while I was away, not just come back to my last couple of [+171 gold] and have to look at my stats and achievements to guess what happened.

**Comment by seiyria** [comment]
It's tough to say what's important because that's entirely subjective.

**Comment by seiyria** [comment]
Additionally the log is only about 50 events long so your important events probably fell off if you were gone for more than an hour.

**Comment by TheParanoidBaboon** [comment]
That's what I'm saying. I suggested a secondary log with less events and a longer memory. I don't think that it's that subjective to sort between achievements and random XP-gold events. But if you don't think it's a good idea, ok.

**Comment by seiyria** [comment]
I unfortunately do not. There is not enough space for something like this
and I have to be selective with how I use it.

It is subjective because some people might consider merchant events
important for example, while others may not (as they can lead to enchants).
I aim for as little config as possible while keeping what I do add
meaningful.
