### ISSUE TITLE
Ability to Delete Character and Start Over

### ISSUE THREAD

**Issue by Vandivier** [IdleLands/IdleLands#537]
As a user, I would like to be able to delete my character and start over.

Note 1: If this is already possible then I would like the instructions added to ./wiki/New-Player-Information
Note 2: I would like this ability in particular because I think I noticed another bug during setup, but I can't replicate because I can't go back to that state.
Note 3: The previous bug I think I saw was that when created a new account via Twitter then created a new character I had to click the confirm/create character button twice to proceed.

**Comment by seiyria** [comment]
This is not possible. There's no reason for this to be possible, as there is no permanent data from character creation that merits a reset - class and gender are changeable during the game. Name is not, but if it becomes a problem it is mod-changeable.

Yes, there is currently a bug where you have to hit create twice. I'm not sure why, I've recorded that bug here: https://github.com/IdleLands/Play/issues/128
