### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#59]
Quests were a highly requested feature in IdleLands throughout its history, and they're finally going to happen.

Quests will need a root action (what you have to do), and maybe they will also have a turn in location (to finish the quest, go to a place). Finishing a quest will earn you a buff. Buffs can be anything from +XP to ... well, anything buffs can currently do. Quests will not have a duration. If you do not want to do a quest, you can reroll the quest for gold. The rewards will be determined when the quest is complete, based on an internal difficulty scalar value (so quests that are 100 steps are given a rating of 1, but quests that are 100000 steps given a rating of maybe 5). They are not going to be shown beforehand to prevent reroll fishing. Quests could also optionally require a region/map for a statistic increase to lock you to a particular map.

Quests would need to be able to specify multiple root actions, in case it wants to pair with things like "owning a certain collectible."

In #33 we talk about end game content, and the idea of global/public quests also comes up. Contributing to these and finishing them (these would be on a timer, and there would be one of them which would reset when the timer is done) would grant a global festival, as well as buffs for the individuals who are online and contributed when the quest finished (a scalar boost based on how much you contributed - likely as a %). There would only be one at a time, probably with a duration ranging from 24 hours to 168 hours (1 week).

Some possible quests:

- do X drunk steps
- step in a map X times
- step on terrain X times
- gain X gold/xp/etc
- Gamble (or do an event) X times
- Win X combats
- Spend X stamina
- Collect a certain collectible
- Kill X bosses

Likely, tiers would increase similarly to how things are in game - 10, 100, 1000, etc and that would determine their reward tier (which would scale the reward and/or the duration). Each stat may need its own scalar (for example, killing bosses is more time consuming, so it would be a scalar of 3, but steps would scale in 10s).

Modifying these for global, per @sedgwick: 

- "Clear the rockslide in Vocalnus! Spend stamina in Vocalnus town to contribute!"
- "Spend gold in Maeles town to help the economy!"

Global achievements should:

- have a REST API you can query to get current globals
- track their progress on your $quests object
- always have a map, sometimes have a region (if the map has at least 10 regions, picking one is probably fine)
- show your contribution, and a global progress bar
- have one to five objectives
- allow for reward collection up to 3 days after it expires
- give good rewards based on participation
- show the old, unclaimed global quest(s) that are still on the quest object. if the global quest does not exist, it should be removed from the $quests object on login. if the timestamp is too old, it should be removed on login.
- show the new quest above the unclaimed one
- announce to the server when it is complete, when it has started, and every 3 hours after it is complete until it expires, counting down how long until it expires (for a total of 24 reminders)

Additionally, new stats will be tracked and new achievements will be given. Some statistics:

- \# quests completed
- quest level total (the scalar)
- \# global quests contributed to

Achievements:

- taskmaster (complete X quests)
- good samaritan (contribute to X global quests)

Number of quests should be governed by a new permanent upgrade (questCapBoost) with a default of 1. Some pets should increase this number, as well as the normal premium upgrade. Patrons should get a sizable boost as well (basically, their patron tier).

Looking for feedback, quest ideas, more "random" types of events that can occur for flavor text.

**Comment by sedgwick** [comment]
General global quest ideas, including the above ones:

- Quests that need to reach a certain amount of resources before timer runs out.
Ex. Spend Stamina in Vocalnus to prepare for an eruption in 2 days. It will take 6000 stamina to prepare the town.
- Variation of above where resources need to be met with no timer.
Ex. The Mage trainer in Frigri needs 2000 macguffins to cast the protection spell on the city.
- Quests that accept as many resources as possible before timer runs out.
Ex. Donate blue crystals to Maeles to help the mage trainer. Accepting donations for 2 days.
- Persistent bosses, a kind of global raid. They are strong, high HP, but don't regen health during combat so everyone can take a stab at it. Since adding things to the map would be tricky, and I imagine you'll add a unique quest tab, I figure this one would be a combat button while you're on the correct map/region, then trigger the usual boss timer (3hr you can try again? maybe sooner for global bosses?).
Ex. Defeat the Grue haunting Norkos Dungeon -3.
- Steps in region/map, fun way to get a bunch of players into maps that aren't usually traversed.
Ex. Trash pickup in Homlet Caves entrance, spend time (steps) picking up litter in the area. 2 days remaining.

Resources that can be used:
- Stamina
- Crystals
- Scrolls (I figure this would be worth a higher reward considering current rarity)
- Items (Selling/donating gear in a region to trigger quest progress? 'help equip new adventurers')
- gold
- salvage (you could potentially let anyone gather salvage, not just those in a guild)

**Comment by seiyria** [comment]
I think salvaging per player might be feasible and reasonable now that I track materials and resources separately, with a way to auto-donate to a guild I think we'll be good to go in that regard.

**Comment by boozledorf** [comment]
Some more ideas:

- Enchant X items
- Change profession X times
  - Change profession to Y (one of the rare professions, cannot roll what you already are)
- Explore X maps

**Comment by sedgwick** [comment]
I'm sure you've got it noted, but lots of potential for achievements here. # of participated global quests, a one off achievement for being the best participant in a global (could also be tiered but 1 off seemed better balanced)
