### ISSUE TITLE
we need some new gold sinks!

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#7]
guilds will be a contributor, but are there any other things in the mean time?

here's one idea:

you can reroll pet attributes, genders, names, and classes for gold.

**Comment by sedgwick** [comment]
**1.** Upgrading gear: Spend X gold to run a BlessItem event on a piece of gear. The higher the item score, the more expensive it gets. And it's still a BlessItem, so you can't pick and choose what stat you boost. Since event rate is static and drops are a little more infrequent now, being able to strengthen what you have seems a little more vital from what I've seen so far. I don't know what pricing should be for balance, but feasibly you would be running yourself penniless if you were to try and max out all your current equipment at your level. Item action, so in this menu. https://i.imgur.com/sxtgrQx.png
**2.** In that same vein, if you like the upgrade idea, if you really want to tinker with an item have a ForsakeItem event option too because why not? Downgrade gear? Break Gear? Same thing, X gold to run the ForsakeItem event for a random gear stat drop. If you have a lot of extra gold, it's just playing the odds of reducing/upgrading the stats you want.
**3.** Pet Rush: Spend X gold to hurry your pet that is on an adventure. Maybe a 1 time limit per adventure, more expensive if more pets on adventure. I'm thinking something like a percent of time remaining removed, so longer missions would be more expensive. Could have an ILP option for this too.
**4.** Pay X gold to remove an injury?
**5.** Gold Sink titles. A set of gold-purchased titles at major increments, 10 million, 1 billion, etc.

**Comment by CyberOnion** [comment]
Town teleports that you can buy via gold or ILP points

**Comment by seiyria** [comment]
zig says: gold based gacha pulls (#18) so we could have a way to roll for large amounts of money.

these gachas could include other scrolls like boss teleport scrolls, event-starting scrolls, enchantment scrolls, teleport to trainer scrolls, teleport to party scrolls

**Comment by Takeces** [comment]
Rerolling of pet adventures. Looking for some short or long adventures? Reroll a single one until you get one that fits what you're looking for.

**Comment by ZeroHands2Feet** [comment]
Not sure what this entail, if even possible. But have a global quest that needs players to donate gold in order to complete.

"Donate 1,000,000,000,000,000 gold to '**_Make A Seiyria Happy_**' Foundation"

**Comment by Brooke-Renna** [comment]
Pet Adventure Empowering (Yes I played Diablo 3):  Spend gold to empower a pet adventure, giving more rewards or a better chance of rarer rewards. Possibly give more XP for pets on the adventure? The gold cost could increase with the number of pets being sent, and/or length of the adventure, and possibly the type of adventure could have a different base cost in case one is more OP (Thinking maybe the pet enhancement one with the astral crystal rewards or something).
