### ISSUE TITLE
Save new players from the fate lake experience

### ISSUE THREAD

**Issue by Aviarium** [IdleLands/IdleLands#749]
At the moment every new player can be dragged into the fate lake area where he might end up dropping to level 1 again. Players who played the game longer and already ascended know, that dropping to 1 is not as bad as it sounds, but it might push newer players away. 

Suggestion: Add a requirement of ascencion 1 to the fate lake teleports

the pools are not that bad since players dont get thousands of providence events there before stumbling out again

**Comment by seiyria** [comment]
I don't think I'd want a requirement this strict. Perhaps level 50 (or 100,
or whatever) to enter would be fine by me, but cutting out the whole first
Ascension might be a bit rough.

I'm not sure a strict level requirement is a good choice either though.
Perhaps there are sooner landmarks that are fairly reasonable?

**Comment by Aviarium** [comment]
the problem there is: the further into the first ascencion, the heavier is the impact of loosing these levels. The first one is the one that needs the longest to work through.
players who play only during the day might need 3-4 weeks to reach lvl 100+, then be afk for a day, drop in there and lose everything - thats a player gone. 

maybe make players more aware of fate events by setting the requirement to event.providence 25 ?

**Comment by seiyria** [comment]
That might be ok. I don't want to cut people out because it does interest
some people and an Ascension can take some time. However having them go
through the pools first is fine with me.

**Comment by sedgwick** [comment]
I think the easiest way to go about it would be:
* Require the Mapceptional achievement for Fate Pools -2, already in game, and add that requirement to all Fate Lake access points.

or 

* Require a collectible from Fate Pools -2 to enter. Both collectibles already have a use (1 for a skill, 1 for a pet), so it could be a new collectible. Would need to keep in mind relaying that information since there are people who do go to Fate Lake on purpose.

I have to agree with @Aviarium that Fate Lake is a pretty brutal experience, and could use some additional way to relay that in game before you start seeing the horror begin in your adventure log. Perhaps adding a requirement would be enough to resolve the issue?

And while we're at it, does Fate Lake offer a rewarding enough experience in its current form? Could it use some additional features, like a collectible, forceEvent tiles for gold? An additional exit to some other rarely visited map is an option too, since currently Fate Lake only drops you around Norkos and it's easy enough to do that party hopping.

**Comment by sedgwick** [comment]
https://github.com/IdleLands/Maps/pull/244

Mapceptional: Fate Pools -2 required to enter Fate Lake TPs now. This way, it's still accessible pre-ascension, but unlikely unless you go out of your way to the Fate Pools early on.
