### ISSUE TITLE
add more achievements

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#8]
https://github.com/IdleLands/IdleLandsOld/tree/master/src/character/achievements
- automatic achievement for collecting each achievement of a certain storyline

**Comment by seiyria** [comment]
* leader: start X parties and gain bonus xp (grant bonus xp for blessxp events)
* follower: join X+Y parties and gain a boost to item finding (possibly for parties)
* solo: track how many steps a player takes while solo, and match it against a week of taking steps for the first tier. no idea what the bonuses could be for this, but the tier that grants a title could come in at 6 months.

**Comment by sedgwick** [comment]
maybe for solo an all around bonus. Maybe the title could be self reliant. A small percentage to all stats as, you have to depend on all your attributes. Possibly a health/con boost for combat, or just boss fights, because they will be harder solo. A kind of heroism skill for battle that lets a solo player have some improved attributes/counterattack kind of stuff happen sometimes for a few rounds.

It's hard to know how much is enough, because it's a big time investment and you can't spend your time grouping up if you want to get it quickly. But if it is underwhelming, then people would just stick with grouping up for better combat.

**Comment by seiyria** [comment]
I want to keep this open but I don't think I will for the time being. Achievements for collectibles of storylines will flood achievements with way too many IMO (given that there are lots of storylines) and the party ones are partially implemented.

I would like to give more to solo players but I don't know if this is the right way to do it.
