### ISSUE TITLE
choices do not seem to take action when they come out of the choice log automatically

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#93]
I think affirmer/denier/indecisive are just going to change: instead of setting the default choice, they should probably just take action on the choice immediately when it gets added to the choice log.

**Comment by sedgwick** [comment]
For some perspective, I'm several days and hundreds of levels into this ascension, and my choice log has been full the entire time, I have manually picked no choices. I should still have had some gear swaps due to random 'yes' results over time, but am still wearing all the starting gear. https://i.imgur.com/74JCMLu.png

edit: This also prevents quests requiring sell choices from being completed unless done manually.  I have several events at the moment set to sell by indecisive, but have had no events trigger the quest. https://i.imgur.com/BLVNySK.png
